global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    consul_sd_configs:
      - server: 'consul.service.consul:8500'
        services: ['prometheus']

  - job_name: 'nomad'
    metrics_path: '/v1/metrics'
    params:
      format: ['prometheus']
    consul_sd_configs:
      - server: 'consul.service.consul:8500'
        services: ['nomad-client']

  - job_name: 'node-exporter'
    consul_sd_configs:
      - server: 'consul.service.consul:8500'
        services: ['node-exporter']

  - job_name: 'fiqo-backend'
    metrics_path: '/actuator/prometheus'
    consul_sd_configs:
      - server: 'consul.service.consul:8500'
        services: ['fiqo-backend']
