global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cilium'
    static_configs:
      - targets:
          - '192.168.99.101:9090'
          - '192.168.99.102:9090'
          - '192.168.99.103:9090'
          - '192.168.99.104:9090'
          - '192.168.99.105:9090'
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'prometheus'
    consul_sd_configs:
      - server: 'consul.service.consul:8500'
        services: ['prometheus']

  - job_name: 'nomad'
    metrics_path: '/v1/metrics'
    params:
      format: ['prometheus']
    consul_sd_configs:
      - server: 'consul.service.consul:8500'
        services: ['nomad-client']

  - job_name: 'consul'
    static_configs:
      - targets:
          - '192.168.99.101:8500'
          - '192.168.99.102:8500'
          - '192.168.99.103:8500'
          - '192.168.99.104:8500'
          - '192.168.99.105:8500'
    metrics_path: '/v1/agent/metrics'
    scheme: 'http'

  - job_name: 'node-exporter'
    consul_sd_configs:
      - server: 'consul.service.consul:8500'
        services: ['node-exporter']

  - job_name: 'fiqo-backend'
    metrics_path: '/actuator/prometheus'
    consul_sd_configs:
      - server: 'consul.service.consul:8500'
        services: ['fiqo-backend']
